[settings]
experimental = true

[oci]
from = "node:24-trixie-slim"

[tasks.build-oci]
# Ceiling paths must be set inline since mise will pull in other config's deps before command is run
run = "MISE_CEILING_PATHS=\"$(cd '{{config_root}}/../..' && pwd)\" mise oci build -C '{{config_root}}' -o '{{config_root}}/.mise-oci'"

[tools]
bun = "1.3.14"
python = "3.14.6"
uv = "0.11.23"
"npm:json-minify" = "1.0.0"
"npm:prettier" = "3.8.4"
"npm:oxfmt" = "0.55.0"
jaq = "3.1.0"
gojq = "0.12.19"
jq = "1.8.1"
"github:caarlos0/jsonfmt" = "0.5.2"
"github:swaggest/json-cli" = "1.11.2"
"github:tdewolff/minify" = "2.24.13"
"github:tidwall/jj" = "1.9.2"
"cargo:sjq" = "0.1.4"
"cargo:jsonxf" = "1.1.1"
"cargo:jsonformat-cli" = "1.0.0"
"cargo:json-pp-rust" = "0.1.0"
"cargo:jsonice" = "0.2.1"
"github:sharkdp/hyperfine" = "1.20.0"
"aqua:dprint/dprint" = "0.54.0"
