[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
confidence-threshold = 0.8

[advisories]
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
  # required for local lint patching until displaydoc 0.2.6 comes out
  "https://github.com/yaahc/displaydoc",
]
