[workspace]
release = false
publish = false
git_tag_enable = true
changelog_update = true
git_release_name = "{{ package }} {{ version }}"
git_tag_name = "{{ package }}-v{{ version }}"
release_commits = "^(feat|fix|docs|deprecated)(\\(.+\\))?!?:"

[[package]]
name = "bytes2chars"
release = true
publish = true

[[package]]
name = "jjpwrgem-parse"
release = true
publish = true

[[package]]
name = "jjpwrgem-ui"
release = true
publish = true

[[package]]
name = "jjpwrgem"
release = true
publish = true
git_release_enable = false

[changelog]
commit_parsers = [
  { message = "^(feat|feature)", group = "added" },
  { message = "^changed", group = "changed" },
  { message = "^deprecated", group = "deprecated" },
  { message = "^fix", group = "fixed" },
  { message = "^security", group = "security" },
  { message = "^perf", group = "performance" },
  { message = "^docs", group = "documentation" },
  { message = "^test", group = "tests" },
  { message = "^chore", skip = true },
  { message = "^bench", skip = true },
  { message = "^.*", skip = true },
]
