name: mise setup
description: Install and cache mise tools

runs:
  using: composite
  steps:
    - uses: taiki-e/install-action@e3134ec54b36203e18f2d1e80652058bd078dd91 # v2.77.3
      with:
        tool: cargo-binstall
    - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
