name: Host npm

on:
  workflow_call:
    inputs:
      plan:
        description: Dist release plan JSON payload
        required: true
        type: string

permissions:
  contents: read

jobs:
  host:
    name: host npm
    runs-on: ubuntu-latest
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Copy readme and changelog
        run: |
          cp -f readme.md npm-template/README.md
          cp -f CHANGELOG.md npm-template/CHANGELOG.md

      - name: Pack npm
        run: |
          mkdir -p ./npm
          npm pack ./npm-packages/jjpwrgem --pack-destination ./npm

      - name: Upload npm package artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ github.ref_name }}-npm-package.tgz
          path: ./npm/*.tgz
