name: verify

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-mise
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: mise exec -- hk check --all

  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: cargo build --release --verbose

  test-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: ./.github/actions/setup-mise
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: mise run vscode-bin
      - uses: ./.github/actions/setup-node
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
      - run: pnpm --filter jjpwrgem-vscode test
        env:
          DISPLAY: ":99.0"
