min_version = "2026.5.12"

[settings]
experimental = true
lockfile = true
disable_backends = ["asdf"] # doesn't play nice with lockfiles
idiomatic_version_file_enable_tools = ["node"]

[settings.cargo]
binstall = true

[tools]
hk = "1.48.0"
"aqua:apple/pkl" = "0.31.1"
jq = "1.8.2"
"aqua:pnpm/pnpm" = "11.8.0"

[hooks]
postinstall = "hk install --mise"
